# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CartoonCraftForiOS-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for CartoonCraftForiOS-desktop

end

target 'CartoonCraftForiOS-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
	pod 'Google-Mobile-Ads-SDK'

  # Pods for CartoonCraftForiOS-mobile

end
